/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pencatatan.operator;

/**
 *
 * @author Agus.S
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class dataTernak extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    DefaultTableModel model;
    public dataTernak() {
        initComponents();
        String [] judul = {"Nomer Ternak","Nomer Sapih","Tanggal Lahir / Jenis Kelamin","Jenis Hewan","Nomer Induk / Jantan","Status","Bobot","Kondisi Badan"};
        model = new DefaultTableModel(judul,0);
        tabel.setModel(model);
        tampilkan();
    }

    dataTernak(Object object, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    private void reset(){
        nomer_ternak.setText("");
        tanggal_sapih.setText("");
        tanggal_lahir_kelamin.setText("");
        jenis_hewan.setText("");
        nomer_induk_jantan.setText("");
        status.setText("");
        bobot.setText("");
        kondisi_badan.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        nav = new javax.swing.JPanel();
        text_administrator = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        home_nav = new javax.swing.JPanel();
        icon_home = new javax.swing.JLabel();
        text_dashboard = new javax.swing.JLabel();
        icon_add = new javax.swing.JLabel();
        text_profil = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        text_tentang = new javax.swing.JLabel();
        icon_add2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tetx_kembali = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        nomer_ternak = new javax.swing.JTextField();
        tanggal_sapih = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tanggal_lahir_kelamin = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nomer_induk_jantan = new javax.swing.JTextField();
        bobot = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        kondisi_badan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        hapus = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        buat = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        jenis_hewan = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nav.setBackground(new java.awt.Color(35, 63, 116));
        nav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text_administrator.setBackground(new java.awt.Color(255, 255, 255));
        text_administrator.setFont(new java.awt.Font("Segoe UI Light", 0, 23)); // NOI18N
        text_administrator.setForeground(new java.awt.Color(204, 204, 204));
        text_administrator.setText("Operator");
        text_administrator.setFocusable(false);
        nav.add(text_administrator, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 100, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boss.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nav.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 54, -1, -1));

        home_nav.setBackground(new java.awt.Color(255, 255, 255));
        home_nav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/house.png"))); // NOI18N
        home_nav.add(icon_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        text_dashboard.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        text_dashboard.setForeground(new java.awt.Color(0, 0, 0));
        text_dashboard.setText("Dashboard");
        home_nav.add(text_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        nav.add(home_nav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 212, 200, 43));

        icon_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        nav.add(icon_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 274, -1, -1));

        text_profil.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        text_profil.setForeground(new java.awt.Color(255, 255, 255));
        text_profil.setText("Profil");
        text_profil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_profilMouseClicked(evt);
            }
        });
        nav.add(text_profil, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 273, -1, -1));

        jButton1.setBackground(new java.awt.Color(35, 63, 116));
        jButton1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Log out");
        jButton1.setBorderPainted(false);
        jButton1.setDefaultCapable(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        nav.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, -1, -1));

        text_tentang.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        text_tentang.setForeground(new java.awt.Color(255, 255, 255));
        text_tentang.setText("Tentang");
        text_tentang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_tentangMouseClicked(evt);
            }
        });
        nav.add(text_tentang, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        icon_add2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/about.png"))); // NOI18N
        nav.add(icon_add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        bg.add(nav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 570));

        jPanel2.setBackground(new java.awt.Color(35, 63, 116));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jLabel4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel4KeyPressed(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, -1));

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 760, 30));

        jPanel13.setBackground(new java.awt.Color(35, 63, 116));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Home > Dashboard > Data Ternak");
        jPanel13.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/house.png"))); // NOI18N
        jPanel13.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 30));

        bg.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 690, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Dashboard");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Version 0.0");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 71, -1, 20));

        tetx_kembali.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        tetx_kembali.setForeground(new java.awt.Color(35, 63, 116));
        tetx_kembali.setText("   Kembali");
        tetx_kembali.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(35, 63, 116)));
        tetx_kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tetx_kembaliMouseClicked(evt);
            }
        });
        bg.add(tetx_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 528, 70, 30));

        tabel.setBackground(new java.awt.Color(255, 255, 255));
        tabel.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        tabel.setForeground(new java.awt.Color(0, 0, 0));
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nomer Ternak", "Tanggal Sapih", "Tanggal lahir/tipe kelamin", "Jenis Hewan", "Nomor Induk/Jantan", "Bobot", "Status", "Keterangan"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 710, 160));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Nomer Ternak");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, 20));

        nomer_ternak.setBackground(new java.awt.Color(204, 204, 204));
        nomer_ternak.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        nomer_ternak.setForeground(new java.awt.Color(0, 0, 0));
        nomer_ternak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomer_ternakActionPerformed(evt);
            }
        });
        bg.add(nomer_ternak, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 300, 30));

        tanggal_sapih.setBackground(new java.awt.Color(204, 204, 204));
        tanggal_sapih.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        tanggal_sapih.setForeground(new java.awt.Color(0, 0, 0));
        tanggal_sapih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggal_sapihActionPerformed(evt);
            }
        });
        bg.add(tanggal_sapih, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 300, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Tanggal Sapih");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Tanggal Lahit / Jenis Kelamin");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, 20));

        tanggal_lahir_kelamin.setBackground(new java.awt.Color(204, 204, 204));
        tanggal_lahir_kelamin.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        tanggal_lahir_kelamin.setForeground(new java.awt.Color(0, 0, 0));
        tanggal_lahir_kelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggal_lahir_kelaminActionPerformed(evt);
            }
        });
        bg.add(tanggal_lahir_kelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 300, 30));

        status.setBackground(new java.awt.Color(204, 204, 204));
        status.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        status.setForeground(new java.awt.Color(0, 0, 0));
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        bg.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 310, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Status");
        bg.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 60, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Nomer Induk / Jantan");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, -1, 20));

        nomer_induk_jantan.setBackground(new java.awt.Color(204, 204, 204));
        nomer_induk_jantan.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        nomer_induk_jantan.setForeground(new java.awt.Color(0, 0, 0));
        nomer_induk_jantan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomer_induk_jantanActionPerformed(evt);
            }
        });
        bg.add(nomer_induk_jantan, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 310, 30));

        bobot.setBackground(new java.awt.Color(204, 204, 204));
        bobot.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        bobot.setForeground(new java.awt.Color(0, 0, 0));
        bobot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bobotActionPerformed(evt);
            }
        });
        bg.add(bobot, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 310, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Bobot");
        bg.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 60, 20));

        kondisi_badan.setBackground(new java.awt.Color(204, 204, 204));
        kondisi_badan.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        kondisi_badan.setForeground(new java.awt.Color(0, 0, 0));
        kondisi_badan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kondisi_badanActionPerformed(evt);
            }
        });
        bg.add(kondisi_badan, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 310, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Kondisi Badan");
        bg.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, -1, 20));

        hapus.setBackground(new java.awt.Color(255, 255, 255));
        hapus.setForeground(new java.awt.Color(0, 0, 0));
        hapus.setText("Hapus");
        hapus.setFocusable(false);
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        bg.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, -1, -1));

        batal.setBackground(new java.awt.Color(255, 255, 255));
        batal.setForeground(new java.awt.Color(0, 0, 0));
        batal.setText("Batal");
        batal.setFocusable(false);
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        bg.add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, -1, -1));

        buat.setBackground(new java.awt.Color(255, 255, 255));
        buat.setForeground(new java.awt.Color(0, 0, 0));
        buat.setText("Buat");
        buat.setFocusable(false);
        buat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buatActionPerformed(evt);
            }
        });
        bg.add(buat, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, -1));

        ubah.setBackground(new java.awt.Color(255, 255, 255));
        ubah.setForeground(new java.awt.Color(0, 0, 0));
        ubah.setText("Ubah");
        ubah.setFocusable(false);
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        bg.add(ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, -1, -1));

        jenis_hewan.setBackground(new java.awt.Color(204, 204, 204));
        jenis_hewan.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jenis_hewan.setForeground(new java.awt.Color(0, 0, 0));
        jenis_hewan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenis_hewanActionPerformed(evt);
            }
        });
        bg.add(jenis_hewan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 300, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Jenis Hewan");
        bg.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, 20));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 570));

        setSize(new java.awt.Dimension(958, 561));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void text_profilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_profilMouseClicked
        // TODO add your handling code here:
        new Profil().show();
        this.dispose();
    }//GEN-LAST:event_text_profilMouseClicked

    private void jLabel4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4KeyPressed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void text_tentangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_tentangMouseClicked
        // TODO add your handling code here:
        new About().show();
        this.dispose();
    }//GEN-LAST:event_text_tentangMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        new Login().show();
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void tetx_kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tetx_kembaliMouseClicked
        // TODO add your handling code here:
        new HomepageOperator().show();
        this.dispose();
    }//GEN-LAST:event_tetx_kembaliMouseClicked

    private void nomer_ternakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomer_ternakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomer_ternakActionPerformed

    private void tanggal_sapihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggal_sapihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggal_sapihActionPerformed

    private void tanggal_lahir_kelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggal_lahir_kelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggal_lahir_kelaminActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void nomer_induk_jantanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomer_induk_jantanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomer_induk_jantanActionPerformed

    private void bobotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bobotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bobotActionPerformed

    private void kondisi_badanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kondisi_badanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kondisi_badanActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        try {
            // TODO add your handling code here:
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/ternak","root","");
            cn.createStatement().executeUpdate("delete from ternak where nomer_ternak='"+nomer_ternak.getText()+"'");
            tampilkan();
            reset();
        } catch (SQLException ex) {
            Logger.getLogger(dataTernak.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void buatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buatActionPerformed
        try {
            // TODO add your handling code here:
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/ternak","root","");
            cn.createStatement().executeUpdate("insert into ternak value"+"('"+nomer_ternak.getText()+"','"+tanggal_sapih.getText()+"','"+tanggal_lahir_kelamin.getText()+"','"+jenis_hewan.getText()+"','"+nomer_induk_jantan.getText()+"','"+status.getText()+"','"+bobot.getText()+"','"+kondisi_badan.getText()+"')");
            tampilkan();
            reset();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"mohon diisi semua kolom");
        }
    }//GEN-LAST:event_buatActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        try {
            // TODO add your handling code here:
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/ternak","root","");
            cn.createStatement().executeUpdate("update ternak set nomer_ternak ='"+nomer_ternak.getText()+"',tanggal_sapih ='"+tanggal_sapih.getText()+"',tanggal_lahir_kelamin ='"+tanggal_lahir_kelamin.getText()+"',jenis_hewan ='"+jenis_hewan.getText()+"',nomer_induk_jantan ='"+nomer_induk_jantan.getText()+"',status ='"+status.getText()+"',bobot ='"+bobot.getText()+"',kondisi_badan ='"+kondisi_badan.getText()+"'");
            tampilkan();
            reset();
        } catch (SQLException ex) {
            Logger.getLogger(dataTernak.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ubahActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_batalActionPerformed

    private void jenis_hewanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenis_hewanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenis_hewanActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        int i = tabel.getSelectedRow();
        
        if(i>-1){
            nomer_ternak.setText(model.getValueAt(i, 0).toString());
            tanggal_sapih.setText(model.getValueAt(i, 1).toString());
            tanggal_lahir_kelamin.setText(model.getValueAt(i, 2).toString());
            jenis_hewan.setText(model.getValueAt(i, 3).toString());
            nomer_induk_jantan.setText(model.getValueAt(i, 4).toString());
            status.setText(model.getValueAt(i, 5).toString());
            bobot.setText(model.getValueAt(i, 6).toString());
            kondisi_badan.setText(model.getValueAt(i, 7).toString());
            
        }
    }//GEN-LAST:event_tabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataTernak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataTernak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataTernak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataTernak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dataTernak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JPanel bg;
    private javax.swing.JTextField bobot;
    private javax.swing.JButton buat;
    private javax.swing.JButton hapus;
    private javax.swing.JPanel home_nav;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel icon_add;
    private javax.swing.JLabel icon_add2;
    private javax.swing.JLabel icon_home;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jenis_hewan;
    private javax.swing.JTextField kondisi_badan;
    private javax.swing.JPanel nav;
    private javax.swing.JTextField nomer_induk_jantan;
    private javax.swing.JTextField nomer_ternak;
    private javax.swing.JTextField status;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField tanggal_lahir_kelamin;
    private javax.swing.JTextField tanggal_sapih;
    private javax.swing.JLabel tetx_kembali;
    private javax.swing.JLabel text_administrator;
    private javax.swing.JLabel text_dashboard;
    private javax.swing.JLabel text_profil;
    private javax.swing.JLabel text_tentang;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables

    private void tampilkan() {
        //To change body of generated methods, choose Tools | Templates.
        int row = tabel.getRowCount();
        for(int a = 0; a<row;a++){
            model.removeRow(0);
        }
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/ternak","root","");
            ResultSet rs = cn.createStatement().executeQuery("SELECT * FROM ternak");
            while(rs.next()){
                String data [] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)};
                model.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(dataTernak.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
}
