/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pencatatan.operator;

import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.JOptionPane;
import koneksi.conekoperator;



/**
 *
 * @author Agus.S
 */
public class Login extends javax.swing.JFrame {
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        textWelcome = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelUser = new javax.swing.JLabel();
        iconUser = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        iconPass = new javax.swing.JLabel();
        labelUser1 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        textLogin = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(32, 65, 116));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/goat.png"))); // NOI18N
        jPanel2.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 140, 150));

        textWelcome.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        textWelcome.setText("WELCOME ");
        jPanel2.add(textWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 360));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelUser.setBackground(new java.awt.Color(204, 204, 204));
        labelUser.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        labelUser.setForeground(new java.awt.Color(51, 51, 51));
        labelUser.setText("Username");
        jPanel1.add(labelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 140, 30));

        iconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        jPanel1.add(iconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 30, 30));

        user.setBackground(new java.awt.Color(204, 204, 204));
        user.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        user.setForeground(new java.awt.Color(51, 51, 51));
        user.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        user.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userFocusGained(evt);
            }
        });
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 278, 30));

        iconPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/password.png"))); // NOI18N
        jPanel1.add(iconPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 30, 30));

        labelUser1.setBackground(new java.awt.Color(204, 204, 204));
        labelUser1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        labelUser1.setForeground(new java.awt.Color(51, 51, 51));
        labelUser1.setText("Password");
        jPanel1.add(labelUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 140, 30));

        pass.setBackground(new java.awt.Color(204, 204, 204));
        pass.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        pass.setForeground(new java.awt.Color(51, 51, 51));
        pass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passFocusGained(evt);
            }
        });
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 280, 30));

        textLogin.setFont(new java.awt.Font("Segoe UI Light", 1, 30)); // NOI18N
        textLogin.setForeground(new java.awt.Color(51, 51, 51));
        textLogin.setText("Login");
        jPanel1.add(textLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 130, 50));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        close.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                closeKeyPressed(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 20, 20));

        btnLogin.setBackground(new java.awt.Color(204, 204, 204));
        btnLogin.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 0, 0));
        btnLogin.setText("Login");
        btnLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(32, 65, 116), new java.awt.Color(32, 65, 116), new java.awt.Color(32, 65, 116), new java.awt.Color(32, 65, 116)));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 160, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 410, 360));

        setSize(new java.awt.Dimension(728, 358));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void userFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userFocusGained
        // TODO add your handling code here:
        user.setText("");
    }//GEN-LAST:event_userFocusGained

    private void passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFocusGained
        pass.setText("");
    }//GEN-LAST:event_passFocusGained

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try {
            Statement statement =(Statement) conekoperator.GetConnection().createStatement();
            ResultSet result=statement.executeQuery("select*from operator where "+"username='"+user.getText()+"'");
            if (result.next()){
                if (pass.getText().equals(result.getString("password"))){
                   new HomepageOperator().show();
                    this.dispose();

                }else{
                    JOptionPane.showMessageDialog(this,"Password salah","pesan",JOptionPane.WARNING_MESSAGE);
                    pass.setText("");
                    user.requestFocus();
                }
            }else{
            JOptionPane.showMessageDialog(this,"User Tidak Ditemukan","pesan",JOptionPane.WARNING_MESSAGE);
                user.setText("");
                pass.setText("");
                user.requestFocus();
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(this,"Gagal!! ", "Pesan",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void closeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_closeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_closeKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel close;
    private javax.swing.JLabel iconPass;
    private javax.swing.JLabel iconUser;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelUser;
    private javax.swing.JLabel labelUser1;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel textLogin;
    private javax.swing.JLabel textWelcome;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
