/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pencatatan.operator;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pencatatan.Login;
/**
 *
 * @author Agus.S
 */
public class Pencatatan extends javax.swing.JFrame {

    /**
     * Creates new form Pencatatan
     */
    DefaultTableModel model;
    DefaultTableModel model1;
    DefaultTableModel model2;
    public Pencatatan() {
        initComponents();
        String [] judul = {"Nomer Ternak","Nomer Sapih","Tanggal Lahir / Jenis Kelamin","Jenis Hewan","Nomer Induk / Jantan","Status","Bobot","Kondisi Badan"};
        String [] judul1 = {"No","Nomer Ternak","Tgl Penimbangan","Bobot","Keterangan"};
        String [] judul2 = {"No","Nomer Ternak","Tanggal","Gejala","Diagnosa","Tindakan","Keterangan"};
        model = new DefaultTableModel(judul,0);
        model1 = new DefaultTableModel(judul1,1);
        model2 = new DefaultTableModel(judul2,1);
        tabel.setModel(model);
        tabel1.setModel(model1);
        tabel2.setModel(model2);
        tampilkan();
        tampilkan1();
        tampilkan2();
    }
    
    private void reset(){
        no.setText("");
        nomer_ternak.setText("");
        tanggal_penimbangan.setDate(null);
        bobot.setText("");
        keterangan.setText("");
    }
    
    private void reset1(){
        no_1.setText("");
        nomer_ternak1.setText("");
        tanggal.setDate(null);
        gejala.setText("");
        diagnosa.setText("");
        tindakan.setText("");
        keterangan1.setText("");
    }
    
    private void ubah1(){
        try {
            // TODO add your handling code here:
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/ternak","root","");
                      
            cn.createStatement().executeUpdate("update riwayat_bobot set nomer_ternak ='"+nomer_ternak.getText()+"',tanggal_penimbangan ='"+dateFormat.format(tanggal_penimbangan.getDate())+"',bobot='"+bobot.getText()+"',keterangan='"+keterangan.getText()+"' where no ='"+no.getText()+"'");
                        
            tampilkan1();
            JOptionPane.showMessageDialog(null,"Berhasil disimpan....!!");
            reset();
        } catch (SQLException ex){
            JOptionPane.showMessageDialog(null,"Data Required");
            Logger.getLogger(Pencatatan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void ubah2(){
        try {
            SimpleDateFormat dateFormat1 = new SimpleDateFormat("yyyy-MM-dd");
            Connection cn1 = DriverManager.getConnection("jdbc:mysql://localhost/ternak","root","");
            cn1.createStatement().executeUpdate("update riwayat_kesehatan set nomer_ternak1 ='"+nomer_ternak1.getText()+"',tanggal'"+dateFormat1.format(tanggal.getDate())+"',gejala'"+gejala.getText()+"',diagnosa'"+diagnosa.getText()+"',tindakan'"+tindakan.getText()+"',keterangan'"+keterangan1.getText()+"' where no ='"+no_1.getText()+"'");
            JOptionPane.showMessageDialog(null,"Berhasil disimpan....!!");
            reset();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Data Required");
            Logger.getLogger(Pencatatan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tetx_kembali = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel1 = new javax.swing.JTable();
        buat = new javax.swing.JButton();
        keterangan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        bobot = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tanggal_penimbangan = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        nomer_ternak = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel2 = new javax.swing.JTable();
        no_ternak1 = new javax.swing.JLabel();
        nomer_ternak1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tanggal = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        gejala = new javax.swing.JTextField();
        keterangan1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tindakan = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        diagnosa = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        batal = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        ubah_kesehatan = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        no = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        no_1 = new javax.swing.JTextField();
        no1 = new javax.swing.JLabel();
        ubah_bobot = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(35, 63, 116));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jLabel4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel4KeyPressed(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, -1, -1));

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 30));

        jPanel13.setBackground(new java.awt.Color(35, 63, 116));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Home > Pencatatan");
        jPanel13.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/house.png"))); // NOI18N
        jPanel13.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 30));

        bg.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 940, 30));

        tetx_kembali.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        tetx_kembali.setForeground(new java.awt.Color(35, 63, 116));
        tetx_kembali.setText("   Kembali");
        tetx_kembali.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(35, 63, 116)));
        tetx_kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tetx_kembaliMouseClicked(evt);
            }
        });
        bg.add(tetx_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 140, 70, 28));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Home");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Version 0.0");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 50, 50, 20));

        tabel1.setBackground(new java.awt.Color(255, 255, 255));
        tabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        tabel1.setForeground(new java.awt.Color(0, 0, 0));
        tabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Nomer Ternak", "Tgl Penimbangan", "Bobot", "Keterangan"
            }
        ));
        tabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel1);

        bg.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 330, 190));

        buat.setBackground(new java.awt.Color(255, 255, 255));
        buat.setForeground(new java.awt.Color(0, 0, 0));
        buat.setText("Buat");
        buat.setFocusable(false);
        buat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buatActionPerformed(evt);
            }
        });
        bg.add(buat, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        keterangan.setBackground(new java.awt.Color(204, 204, 204));
        keterangan.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        keterangan.setForeground(new java.awt.Color(0, 0, 0));
        keterangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keteranganActionPerformed(evt);
            }
        });
        bg.add(keterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 180, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Keterangan");
        bg.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, -1, 20));

        bobot.setBackground(new java.awt.Color(204, 204, 204));
        bobot.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        bobot.setForeground(new java.awt.Color(0, 0, 0));
        bobot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bobotActionPerformed(evt);
            }
        });
        bg.add(bobot, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 180, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Bobot");
        bg.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, 20));

        tanggal_penimbangan.setBackground(new java.awt.Color(204, 204, 204));
        tanggal_penimbangan.setForeground(new java.awt.Color(0, 0, 0));
        tanggal_penimbangan.setDateFormatString("yyyy-MM-dd");
        tanggal_penimbangan.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        tanggal_penimbangan.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tanggal_penimbanganPropertyChange(evt);
            }
        });
        bg.add(tanggal_penimbangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 180, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Tanggal Penimbangan");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, 20));

        nomer_ternak.setBackground(new java.awt.Color(204, 204, 204));
        nomer_ternak.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        nomer_ternak.setForeground(new java.awt.Color(0, 0, 0));
        nomer_ternak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomer_ternakActionPerformed(evt);
            }
        });
        bg.add(nomer_ternak, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 180, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Nomer Ternak");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, 20));

        tabel.setBackground(new java.awt.Color(255, 255, 255));
        tabel.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        tabel.setForeground(new java.awt.Color(0, 0, 0));
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nomer Ternak", "Tanggal Sapih", "Tanggal lahir/tipe kelamin", "Jenis Hewan", "Nomor Induk/Jantan", "Bobot", "Status", "Keterangan"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 520, 120));

        tabel2.setBackground(new java.awt.Color(255, 255, 255));
        tabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        tabel2.setForeground(new java.awt.Color(0, 0, 0));
        tabel2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nomer Ternak", "Tanggal", "Gejala", "Diagnosa", "Tindakan", "Keterangan"
            }
        ));
        tabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabel2);

        bg.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 400, 180));

        no_ternak1.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        no_ternak1.setForeground(new java.awt.Color(51, 51, 51));
        no_ternak1.setText("Nomer Ternak");
        bg.add(no_ternak1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, -1, 20));

        nomer_ternak1.setBackground(new java.awt.Color(204, 204, 204));
        nomer_ternak1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        nomer_ternak1.setForeground(new java.awt.Color(0, 0, 0));
        nomer_ternak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomer_ternak1ActionPerformed(evt);
            }
        });
        bg.add(nomer_ternak1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 190, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Tanggal");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, -1, 20));

        tanggal.setBackground(new java.awt.Color(204, 204, 204));
        tanggal.setForeground(new java.awt.Color(0, 0, 0));
        tanggal.setDateFormatString("yyyy-MM-dd");
        tanggal.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        tanggal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tanggalPropertyChange(evt);
            }
        });
        bg.add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, 190, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Gejala");
        bg.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 550, -1, 20));

        gejala.setBackground(new java.awt.Color(204, 204, 204));
        gejala.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        gejala.setForeground(new java.awt.Color(0, 0, 0));
        gejala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gejalaActionPerformed(evt);
            }
        });
        bg.add(gejala, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 570, 190, 30));

        keterangan1.setBackground(new java.awt.Color(204, 204, 204));
        keterangan1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        keterangan1.setForeground(new java.awt.Color(0, 0, 0));
        keterangan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keterangan1ActionPerformed(evt);
            }
        });
        bg.add(keterangan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 520, 190, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Keterangan");
        bg.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 500, 70, 20));

        tindakan.setBackground(new java.awt.Color(204, 204, 204));
        tindakan.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        tindakan.setForeground(new java.awt.Color(0, 0, 0));
        tindakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tindakanActionPerformed(evt);
            }
        });
        bg.add(tindakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 470, 190, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Tindakan");
        bg.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 450, 60, 20));

        diagnosa.setBackground(new java.awt.Color(204, 204, 204));
        diagnosa.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        diagnosa.setForeground(new java.awt.Color(0, 0, 0));
        diagnosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagnosaActionPerformed(evt);
            }
        });
        bg.add(diagnosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 420, 190, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Diagnosa");
        bg.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, 100, 20));

        batal.setBackground(new java.awt.Color(255, 255, 255));
        batal.setForeground(new java.awt.Color(0, 0, 0));
        batal.setText("Batal");
        batal.setFocusable(false);
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        bg.add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Tabel riwayat kesehatan");
        bg.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, -1, -1));

        ubah_kesehatan.setBackground(new java.awt.Color(255, 255, 255));
        ubah_kesehatan.setForeground(new java.awt.Color(0, 0, 0));
        ubah_kesehatan.setText("Ubah Kesehatan");
        ubah_kesehatan.setFocusable(false);
        ubah_kesehatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubah_kesehatanActionPerformed(evt);
            }
        });
        bg.add(ubah_kesehatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 570, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Pencatatan");
        bg.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Tabel ternak");
        bg.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Tabel riwayat bobot");
        bg.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, -1, -1));

        no.setBackground(new java.awt.Color(204, 204, 204));
        no.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        no.setForeground(new java.awt.Color(0, 0, 0));
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });
        bg.add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 180, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("No");
        bg.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, 20));

        no_1.setBackground(new java.awt.Color(204, 204, 204));
        no_1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        no_1.setForeground(new java.awt.Color(0, 0, 0));
        no_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_1ActionPerformed(evt);
            }
        });
        bg.add(no_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 190, 30));

        no1.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        no1.setForeground(new java.awt.Color(51, 51, 51));
        no1.setText("No");
        bg.add(no1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 20, 20));

        ubah_bobot.setBackground(new java.awt.Color(255, 255, 255));
        ubah_bobot.setForeground(new java.awt.Color(0, 0, 0));
        ubah_bobot.setText("Ubah Bobot");
        ubah_bobot.setFocusable(false);
        ubah_bobot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubah_bobotActionPerformed(evt);
            }
        });
        bg.add(ubah_bobot, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 570, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4KeyPressed

    private void tetx_kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tetx_kembaliMouseClicked
        // TODO add your handling code here:
        new HomepageOperator().show();
        this.dispose();
    }//GEN-LAST:event_tetx_kembaliMouseClicked

    private void tabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel1MouseClicked
        // TODO add your handling code here:
        int i = tabel1.getSelectedRow();

        if(i>-1){
            no.setText(model1.getValueAt(i, 0).toString());
            nomer_ternak.setText(model1.getValueAt(i, 1).toString());
            bobot.setText(model1.getValueAt(i, 3).toString());
            keterangan.setText(model1.getValueAt(i, 4).toString());
        }
        try {
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)model1.getValueAt(i, 2).toString());
            tanggal_penimbangan.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(dataTernak.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tabel1MouseClicked

    private void buatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buatActionPerformed
        try {
            // TODO add your handling code here:
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            SimpleDateFormat dateFormat1 = new SimpleDateFormat("yyyy-MM-dd");

            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/ternak","root","");
            Connection cn1 = DriverManager.getConnection("jdbc:mysql://localhost/ternak","root","");
            
            cn.createStatement().executeUpdate("insert into riwayat_bobot value"+"('"+no.getText()+"','"+nomer_ternak.getText()+"','"+dateFormat.format(tanggal_penimbangan.getDate())+"','"+bobot.getText()+"','"+keterangan.getText()+"')");
            cn1.createStatement().executeUpdate("insert into riwayat_kesehatan value"+"('"+no_1.getText()+"','"+nomer_ternak1.getText()+"','"+dateFormat1.format(tanggal.getDate())+"','"+gejala.getText()+"','"+diagnosa.getText()+"','"+tindakan.getText()+"','"+keterangan1.getText()+"')");
            
            tampilkan1();
            tampilkan2();
            JOptionPane.showMessageDialog(null,"Berhasil disimpan....!!");
            reset();
            reset1();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Data Required");
        }
    }//GEN-LAST:event_buatActionPerformed

    private void keteranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keteranganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keteranganActionPerformed

    private void bobotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bobotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bobotActionPerformed

    private void tanggal_penimbanganPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tanggal_penimbanganPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggal_penimbanganPropertyChange

    private void nomer_ternakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomer_ternakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomer_ternakActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        int i = tabel.getSelectedRow();

        if(i>-1){
            nomer_ternak.setText(model.getValueAt(i, 0).toString());
            nomer_ternak1.setText(model.getValueAt(i, 0).toString());

        }
    }//GEN-LAST:event_tabelMouseClicked

    private void tabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel2MouseClicked
        // TODO add your handling code here:
        int i = tabel2.getSelectedRow();

        if(i>-1){
            no_1.setText(model2.getValueAt(i, 0).toString());
            nomer_ternak1.setText(model2.getValueAt(i, 1).toString());
            gejala.setText(model2.getValueAt(i, 3).toString());
            diagnosa.setText(model2.getValueAt(i, 4).toString());
            tindakan.setText(model2.getValueAt(i, 5).toString());
            keterangan1.setText(model2.getValueAt(i, 6).toString());
        }
        try {
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)model2.getValueAt(i, 2).toString());
            tanggal.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(dataTernak.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tabel2MouseClicked

    private void nomer_ternak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomer_ternak1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomer_ternak1ActionPerformed

    private void tanggalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tanggalPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalPropertyChange

    private void gejalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gejalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gejalaActionPerformed

    private void keterangan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keterangan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keterangan1ActionPerformed

    private void tindakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tindakanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tindakanActionPerformed

    private void diagnosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagnosaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diagnosaActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
        reset();
        reset1();
    }//GEN-LAST:event_batalActionPerformed

    private void ubah_kesehatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubah_kesehatanActionPerformed
        ubah2();
    }//GEN-LAST:event_ubah_kesehatanActionPerformed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noActionPerformed

    private void no_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_1ActionPerformed

    private void ubah_bobotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubah_bobotActionPerformed
        // TODO add your handling code here:
        ubah1();
    }//GEN-LAST:event_ubah_bobotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pencatatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pencatatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pencatatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pencatatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pencatatan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JPanel bg;
    private javax.swing.JTextField bobot;
    private javax.swing.JButton buat;
    private javax.swing.JTextField diagnosa;
    private javax.swing.JTextField gejala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField keterangan;
    private javax.swing.JTextField keterangan1;
    private javax.swing.JTextField no;
    private javax.swing.JLabel no1;
    private javax.swing.JTextField no_1;
    private javax.swing.JLabel no_ternak1;
    private javax.swing.JTextField nomer_ternak;
    private javax.swing.JTextField nomer_ternak1;
    private javax.swing.JTable tabel;
    private javax.swing.JTable tabel1;
    private javax.swing.JTable tabel2;
    private com.toedter.calendar.JDateChooser tanggal;
    private com.toedter.calendar.JDateChooser tanggal_penimbangan;
    private javax.swing.JLabel tetx_kembali;
    private javax.swing.JTextField tindakan;
    private javax.swing.JButton ubah_bobot;
    private javax.swing.JButton ubah_kesehatan;
    // End of variables declaration//GEN-END:variables

    private void tampilkan() {
        //To change body of generated methods, choose Tools | Templates.
        int row = tabel.getRowCount();
        for(int a = 0; a<row;a++){
            model.removeRow(0);
        }
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/ternak","root","");
            ResultSet rs = cn.createStatement().executeQuery("SELECT * FROM ternak");
            while(rs.next()){
                String data [] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)};
                model.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Pencatatan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void tampilkan1() {
        //To change body of generated methods, choose Tools | Templates.
        int row1 = tabel1.getRowCount();
        for(int a = 0; a<row1;a++){
            model1.removeRow(0);
        }
        try {
            Connection cn1 = DriverManager.getConnection("jdbc:mysql://localhost/ternak","root","");
            ResultSet rs1 = cn1.createStatement().executeQuery("SELECT * FROM riwayat_bobot");
            while(rs1.next()){
                String data1 [] = {rs1.getString(1),rs1.getString(2),rs1.getString(3),rs1.getString(4),rs1.getString(5)};
                model1.addRow(data1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Pencatatan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void tampilkan2() {
        //To change body of generated methods, choose Tools | Templates.
        int row2 = tabel2.getRowCount();
        for(int a = 0; a<row2;a++){
            model2.removeRow(0);
        }
        try {
            Connection cn2 = DriverManager.getConnection("jdbc:mysql://localhost/ternak","root","");
            ResultSet rs2 = cn2.createStatement().executeQuery("SELECT * FROM riwayat_kesehatan");
            while(rs2.next()){
                String data2 [] = {rs2.getString(1),rs2.getString(2),rs2.getString(3),rs2.getString(4),rs2.getString(5),rs2.getString(6),rs2.getString(7)};
                model2.addRow(data2);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Pencatatan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
